CREATE DATABASE PROJETODSI202;

USE PROJETODSI202;

CREATE TABLE EMPRESA(
	CDEMPRESA INT PRIMARY KEY AUTO_INCREMENT,
    NOMEEMPRESA VARCHAR(255),
    CNPJEMPRESA VARCHAR(255),
    SENHAEMPRESA VARCHAR(255),
    RAMOEMPRESA VARCHAR(255)
);

insert into empresa (nomeempresa, senhaempresa) values (banana, uva)



